# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88f9115fb320f7d44f5dba1fbcb92e73bd11e9790134fa747da3bbe9c7ad0f6c4a7350007b13fc55c275f30f1342ecdb64de028d24900598ebaac53426541d6b

test:
  secret_key_base: 550304aad7eee5c2ecd7b609c19bb8be54a0f9058496ec92ff57baa50781fb6d22df2e0b7ca537f171da9ccaa0bb30323968e82d87987746866ea9c0431aefe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
